name: CI compile

on:
  push:
    branches:
      - CI_new
  pull_request:
    branches:
      - CI_new
      
jobs:
  run-scripts:
    container:
    image: continuumio/miniconda3:4.12.0
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
        
      - name: install dependencies
        run: |
          apt update -y
          apt-get install openmpi-bin libopenmpi-dev        
      - name: Ejecutar serial code
        working-directory: ./MDS1
        run: |
          cd PROGRAM
          chmod +x Makefile
          make
      - name: Ejecutar mpi code
        working-directory: ./MDP-DoubleWork
        run: |
          cd PROGRAM
          chmod +x Makefile
          make
