name: CI compile

on:
  push:
    branches:
      - CI_new
  pull_request:
    branches:
      - CI_new
      
jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: continuumio/miniconda3:4.12.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  
      - name: Update packages
        run: |
          apt-get update
          apt-get install build-essential
          apt-get install -y --no-install-recommends openmpi-bin libopenmpi-dev
      - name: Ejecutar serial code
        working-directory: ./MDS1
        run: |
          cd PROGRAM
          chmod +x Makefile
          make
      - name: Ejecutar mpi code
        working-directory: ./MDP-DoubleWork
        run: |
          cd PROGRAM
          chmod +x Makefile
          make

